### ISSUE TITLE
Consider adding node_modules to .gitignore and removing directory from repo

### ISSUE THREAD

**Issue by openjck** [mozilla/mdv2-prototype#1]
It's not a hard and fast rule, but most projects at Mozilla don't keep *node_modules* in source control. They list *node_modules* in *.gitignore* to instruct Git to ignore the directory and provide setup instructions that tell other developers to run *npm install* before using the project. See [fhwr-unflattener](https://github.com/mozilla/fhwr-unflattener) as a simple example of that approach.

There are pros and cons to keeping *node_modules* out of source control, so what you decide to do will depend on your needs. But maybe other front-end devs from around the org, like @darkwing, @spasovski, @hamilton, and @jpetto could offer some of their opinions. :smiley:

**Comment by ecomerford** [comment]
Solved by PRs #2 and #3! Thanks for the feedback, @openjck
