### ISSUE TITLE
Aggregate statistics broken for scalars

### ISSUE THREAD

**Issue by georgf** [mozilla/mdv2-prototype#36]
(This originally came up in #34)

Switching to `scalars_devtools_onboarding_is_devtools_user` results (in the summary view) in the median value of infinity.
This seems to come from `getLastBucketUpper()` doing a div by `0` as `buckets[buckets.length - 2]` is `0.`
This is not a new issue, it just is visible now because we're actively loading different data files now (we didn't before).

Chris mentioned:
> `getLastBucketUpper` has commented out code that requires information about what the type of measurement is. We don't have that information, but `scalars_devtools_onboarding_is_devtools_user` is a metric that requires the special handling. I'm not worried about that at this state as it will require broader changes to make correct.

**Comment by chutten** [comment]
This has been fixed by introducing custom language for boolean and categorical probes in Summary.
