### ISSUE TITLE
Use exponential scale for x-axis of comparison view

### ISSUE THREAD

**Issue by ecomerford** [mozilla/mdv2-prototype#43]
In the current comparison view, both graphs have very long tails, which is not ideal for viewing the main portion of the graph. I'd like to update this so that the x-axis is scaled exponentially, which should "normalize" the graph, as it were, or centralize the main curves.

**Comment by ecomerford** [comment]
@wlach perhaps we could get your input on this? You can see the current version of the graph [here](https://mozilla.github.io/mdv2/), under the comparison view tab.

**Comment by chutten** [comment]
Looks like `x_scale_type: "log",` is all we need for that. https://github.com/metricsgraphics/metrics-graphics/wiki/Axes#x_scale_type
