### ISSUE TITLE
Unify user / client / respondent terminology

### ISSUE THREAD

**Issue by georgf** [mozilla/mdv2-prototype#68]
We're starting to use mixed terminology in the dashboard for "users", "clients" & "respondents".

Let's use a single term here. We defaulted to "user", we can have proposals and collect feedback if we need to change it.

**Comment by chutten** [comment]
There is a complicating factor that we're stating things as proportions. In mdv1 proportions were relative to the number of samples provided... but we've also discussed the usefulness of having the number of users who didn't report any value at all as a value to compare against.

That's where "respondents" came from: meaning "users/clients who have reported any value for the probe". To differentiate from "users/clients who reported other histograms for this set of dimensions, but not this one."

**Comment by georgf** [comment]
Can you give an example of where it's useful to talk only about users that reported a value?
What is a task or typical question for this that we want to support?

**Comment by georgf** [comment]
I know that this was a point of confusion on the old dashboard, i think in general people would expect proportions be to absolute number of users for the selected dimensions.

**Comment by chutten** [comment]
Example of proportions of respondents: 
On loading a page that wants to autoplay media with sound, how often do users hit "Allow", "Not now", "Never"?

In general terms it is "Of users presented with a 'treatment', which 'outcomes' were experienced in which proportions?". A relevant point in these cases is "What %ge of users were presented with 'treatment'?".

**Comment by georgf** [comment]
Ok, i think this is a good use-case that we should track!
We haven't however had a specific design conversation about these kinds of use-cases, we should have that first.

This might not be in scope for the current goals, where we are focused on the ratio for all users of a given set of dimensions.
